name: WakaTime Stats

on:
  schedule:
    - cron: "0 18 * * *" # Daily (UTC)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SECTION_NAME: waka
          COMMIT_MESSAGE: "Updated WakaTime stats"

          # Core stats
          SHOW_TOTAL_CODE_TIME: true
          SHOW_LINES_OF_CODE: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_PROJECTS: true
          SHOW_LANGUAGE: true
          SHOW_EDITORS: true

          # Optional
          SHOW_PROFILE_VIEWS: false
          SHOW_OS: false
          SHOW_UPDATED_DATE: true
